# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:

    app.subscriber.controller.coroutine:
        class: AppBundle\Event\CoroutineControllerListener
        arguments: [ '@controller_resolver']
        tags:
            - { name: kernel.event_subscriber }

    app.artax:
        class: Amp\Artax\DefaultClient

    app.db:
        class: Amp\Mysql\Pool
        factory: Amp\Mysql\pool
        arguments: [ '@="host="~parameter("database_host")~";user="~parameter("database_user")~";pass="~parameter("database_password")~";db="~parameter("database_name")']
