# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.artax:
        class: Amp\Artax\DefaultClient

    app.subscriber.view.generator:
        class: AppBundle\GeneratorViewListener
        tags:
            - { name: kernel.event_subscriber }
